#Simple makefile
# Note: the lines containing commands must start with a tab not spaces.
# Compile source code by typing the command make compile
compile:
	javac GreenScreen.java
# Run the Hello java main class by typing the command make run 
run:
	java GreenScreen sagar.png india.png modified png auto
# Clean the compiled class files by typing the command make clean
clean:
	rm *.class
